config/routes.rb
Rails.application.routes.draw do
  resources :data
  root 'data#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/datum.rb
class Datum < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  before_action :set_datum, only: [:show, :edit, :update, :destroy]

  # GET /data
  # GET /data.json
  def index
    @data = Datum.all
  end

  # GET /data/1
  # GET /data/1.json
  def show
  end

  # GET /data/new
  def new
    @datum = Datum.new
  end

  # GET /data/1/edit
  def edit
  end

  # POST /data
  # POST /data.json
  def create
    @datum = Datum.new(datum_params)

    respond_to do |format|
      if @datum.save
        format.html { redirect_to @datum, notice: 'Data was successfully created.' }
        format.json { render :show, status: :created, location: @datum }
      else
        format.html { render :new }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data/1
  # PATCH/PUT /data/1.json
  def update
    respond_to do |format|
      if @datum.update(datum_params)
        format.html { redirect_to @datum, notice: 'Data was successfully updated.' }
        format.json { render :show, status: :ok, location: @datum }
      else
        format.html { render :edit }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data/1
  # DELETE /data/1.json
  def destroy
    @datum.destroy
    respond_to do |format|
      format.html { redirect_to data_url, notice: 'Data was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_datum
      @datum = Datum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def datum_params
      params.require(:datum).permit(:nama, :email, :notelp, :alamat)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/views/data/_form.html.erb
<%= form_with(model: datum, local: true) do |form| %>
  <% if datum.errors.any? %>
    <div id="error_explanation">
      <h2>Please input the data with correct form:</h2>

      <ul>
      <% datum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nama , "Nama" %>
    <%= form.text_field :nama %>
  </div>

  <div class="field">
    <%= form.label :email , "Email" %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :notelp , "No Telepon" %>
    <%= form.text_field :notelp %>
  </div>

  <div class="field">
    <%= form.label :alamat , "Alamat"%>
    <%= form.text_field :alamat %>
  </div>

  <div class="actions">
    <%= form.submit "Submit Data" %>
  </div>
<% end %>

app/views/data/edit.html.erb
<h1>Editing Data</h1>

<%= render 'form', datum: @datum %>

<%= link_to 'Show', @datum %> |
<%= link_to 'Back', data_path %>

app/views/data/index.html.erb
<p id="notice"><%= notice %></p>

<h1>CRUD Website</h1>
<h3>Welcome to the page</h3>

<table>
  <thead>
    <tr>
      <th>No</th>
      <th>Nama</th>
      <th>Email</th>
      <th>Notelp</th>
      <th>Alamat</th>
      <th>Action</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @data.each_with_index do |datum, i| %>
      <tr>
        <td><%= (i+1) %></td>
        <td><%= datum.nama %></td>
        <td><%= datum.email %></td>
        <td><%= datum.notelp %></td>
        <td><%= datum.alamat %></td>
        <td><%= link_to 'Show', datum %>
            <%= link_to 'Edit', edit_datum_path(datum) %>
            <%= link_to 'Destroy', datum, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Data', new_datum_path %>

app/views/data/new.html.erb
<h1>New Data</h1>

<%= render 'form', datum: @datum %>

<%= link_to 'Back', data_path %>

app/views/data/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Data Details</h1>
<p>
  <strong>Nama:</strong>
  <%= @datum.nama %>
</p>

<p>
  <strong>Email:</strong>
  <%= @datum.email %>
</p>

<p>
  <strong>Notelp:</strong>
  <%= @datum.notelp %>
</p>

<p>
  <strong>Alamat:</strong>
  <%= @datum.alamat %>
</p>

<%= link_to 'Edit Data', edit_datum_path(@datum) %> |
<%= link_to 'Back', data_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRUD</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>